interface PaperData {
  title: string;
  authors: string[];
  abstract: string;
  summary: string;
  keywords: string[];
  citation_apa: string;
  citation_mla: string;
  citation_ieee: string;
  year: number;
  venue: string;
  url: string;
}

function escapeLatex(text: string): string {
  if (!text) return "";
  return text
    .replace(/\\/g, "\\textbackslash{}")
    .replace(/[&%$#_{}]/g, (m) => `\\${m}`)
    .replace(/~/g, "\\textasciitilde{}")
    .replace(/\^/g, "\\textasciicircum{}");
}

export function generatePaperReport(paper: PaperData): void {
  const mlTag = paper.keywords.find((k) => k.startsWith("[ML:"));
  const mlCategory = mlTag ? mlTag.replace("[ML:", "").replace("]", "") : "Uncategorized";
  const filteredKeywords = paper.keywords.filter((k) => !k.startsWith("[ML:"));

  const latex = `\\documentclass[12pt,a4paper]{article}
\\usepackage[margin=1in]{geometry}
\\usepackage{titlesec}
\\usepackage{hyperref}
\\usepackage{enumitem}
\\usepackage{xcolor}
\\usepackage{fancyhdr}
\\usepackage{parskip}

\\definecolor{primary}{HTML}{4F46E5}

\\pagestyle{fancy}
\\fancyhf{}
\\fancyhead[L]{\\textcolor{primary}{\\small Paper Analysis Report}}
\\fancyhead[R]{\\small ${escapeLatex(String(paper.year))}}
\\fancyfoot[C]{\\thepage}

\\hypersetup{
  colorlinks=true,
  linkcolor=primary,
  urlcolor=primary,
  citecolor=primary
}

\\title{\\textcolor{primary}{Paper Analysis Report}\\\\[0.5em]
\\Large ${escapeLatex(paper.title)}}
\\author{${escapeLatex(paper.authors.join(", "))}}
\\date{Published: ${escapeLatex(String(paper.year))} \\quad|\\quad Venue: ${escapeLatex(paper.venue)}}

\\begin{document}
\\maketitle
\\thispagestyle{fancy}

\\section*{Classification}
\\textbf{ML Category:} ${escapeLatex(mlCategory)}

\\section*{AI-Generated Summary}
${escapeLatex(paper.summary)}

\\section*{Abstract}
${escapeLatex(paper.abstract)}

\\section*{Keywords}
\\begin{itemize}[noitemsep]
${filteredKeywords.map((k) => `  \\item ${escapeLatex(k)}`).join("\n")}
\\end{itemize}

\\section*{Citation Formats}

\\subsection*{APA}
\\begin{quote}
\\small ${escapeLatex(paper.citation_apa)}
\\end{quote}

\\subsection*{MLA}
\\begin{quote}
\\small ${escapeLatex(paper.citation_mla)}
\\end{quote}

\\subsection*{IEEE}
\\begin{quote}
\\small ${escapeLatex(paper.citation_ieee)}
\\end{quote}

${paper.url ? `\\section*{Source}
\\url{${paper.url}}` : ""}

\\vfill
\\noindent\\rule{\\textwidth}{0.4pt}
\\begin{center}
\\small\\textit{Generated by Autonomous Research Assistant}
\\end{center}

\\end{document}
`;

  const blob = new Blob([latex], { type: "application/x-latex" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  const safeTitle = paper.title
    .replace(/[^a-zA-Z0-9 ]/g, "")
    .replace(/\s+/g, "_")
    .substring(0, 40);
  a.download = `report_${safeTitle}.tex`;
  a.click();
  URL.revokeObjectURL(url);
}
