export const presentationContent = {
  title: {
    main: "Autonomous Research Assistant",
    subtitle: "AI-powered Paper Discovery, Summarization & Citation Generation",
    author: "Gnaneshwar Reddy D, Yedukondalu Reddy D",
    date: new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long' })
  },
  
  problemStatement: {
    title: "Problem Statement",
    points: [
      "Information overload: 200M+ academic papers available online",
      "Time-consuming manual discovery and filtering of relevant papers",
      "Inconsistent citation formatting across different styles (APA, MLA, IEEE)",
      "Difficulty in quickly understanding paper content without full reading",
      "Fragmented research workflow across multiple tools"
    ]
  },
  
  proposedSolution: {
    title: "Proposed Solution",
    points: [
      "Automated paper discovery from Semantic Scholar (200M+ papers)",
      "AI-powered summarization using Google Gemini 2.5 Flash",
      "ML-based domain classification — 97.25% accuracy (Linear SVM)",
      "Multi-format citation generation (APA, MLA, IEEE)",
      "Unified project-based research management"
    ]
  },
  
  architecture: {
    title: "System Architecture",
    layers: [
      { name: "Presentation Layer", components: "React 18 + TypeScript + Tailwind CSS" },
      { name: "State Management", components: "TanStack Query + React Hook Form" },
      { name: "Authentication", components: "JWT-based Auth (Email/Password)" },
      { name: "Backend Services", components: "Edge Functions (Deno Runtime)" },
      { name: "Database", components: "PostgreSQL + Row Level Security" },
      { name: "External Services", components: "Semantic Scholar API + Gemini AI" }
    ]
  },
  
  techStack: {
    title: "Technology Stack",
    items: [
      { category: "Frontend Framework", technology: "React 18 + Vite + TypeScript" },
      { category: "UI Components", technology: "ShadCN/UI + Radix Primitives" },
      { category: "Styling", technology: "Tailwind CSS + CSS Variables" },
      { category: "Backend", technology: "PostgreSQL + Deno Edge Functions" },
      { category: "AI Model", technology: "Google Gemini 2.5 Flash" },
      { category: "Data Source", technology: "Semantic Scholar API (200M+ papers)" },
      { category: "ML Framework", technology: "scikit-learn (TF-IDF + Linear SVM)" }
    ]
  },
  
  databaseSchema: {
    title: "Database Schema",
    tables: [
      {
        name: "profiles",
        columns: ["id (UUID, PK)", "email (TEXT)", "full_name (TEXT)", "created_at", "updated_at"],
        description: "User profile information linked to auth.users"
      },
      {
        name: "projects",
        columns: ["id (UUID, PK)", "user_id (FK)", "name (TEXT)", "description", "created_at", "updated_at"],
        description: "Research projects owned by users"
      },
      {
        name: "papers",
        columns: ["id (UUID, PK)", "project_id (FK)", "title", "authors[]", "abstract", "summary", "keywords[]", "citations (APA/MLA/IEEE)", "url", "year", "venue"],
        description: "Discovered papers with AI-generated summaries"
      }
    ]
  },
  
  dataFlow: {
    title: "Data Flow Diagram",
    steps: [
      "1. User enters search query in Project page",
      "2. Frontend calls discover-papers Edge Function",
      "3. Edge Function queries Semantic Scholar API",
      "4. Retry logic handles rate limiting (3 attempts, exponential backoff)",
      "5. Gemini 2.5 Flash generates summaries, keywords & domain classification",
      "6. Citation generator creates APA/MLA/IEEE formats",
      "7. Enriched papers stored in PostgreSQL with RLS",
      "8. Results displayed in real-time to user"
    ]
  },
  
  keyFeatures: {
    title: "Key Features",
    features: [
      {
        name: "Smart Discovery",
        description: "Search 200M+ academic papers via Semantic Scholar API with retry & AI fallback"
      },
      {
        name: "AI Summarization",
        description: "2-3 sentence summaries generated by Gemini 2.5 Flash for quick understanding"
      },
      {
        name: "ML Domain Classification",
        description: "97.25% accuracy across 6 research domains using tuned Linear SVM"
      },
      {
        name: "Auto Citations",
        description: "One-click citation generation in APA, MLA, and IEEE formats"
      },
      {
        name: "Project Management",
        description: "Organize papers into research projects with full CRUD operations"
      }
    ]
  },
  
  aiPipeline: {
    title: "AI Processing Pipeline",
    stages: [
      {
        stage: "Input",
        description: "Paper abstract (up to 2000 characters)"
      },
      {
        stage: "Processing",
        description: "Gemini 2.5 Flash via AI Gateway"
      },
      {
        stage: "Summarization",
        description: "Concise 2-3 sentence summary extraction"
      },
      {
        stage: "Keywords",
        description: "5-7 relevant academic keywords"
      },
      {
        stage: "Classification",
        description: "Domain label from 6-class taxonomy"
      }
    ]
  },

  mlDataset: {
    title: "Dataset & Preprocessing",
    points: [
      "Dataset: Cornell University arXiv Papers (Kaggle) — 1.7M+ papers, CC0 license",
      "Sampled 18,000 papers (3,000 per category) across 6 distinct domains",
      "Categories: Computer Vision, NLP, Astrophysics, Combinatorics, Neuroscience, HEP Theory",
      "Preprocessing: Lowercasing, stopword removal, lemmatization, title weighting (2×)",
      "Feature extraction: TF-IDF — 50,000 features, n-gram range (1,3), sublinear TF",
      "Train/Test split: 80/20 stratified (14,400 train / 3,600 test)"
    ]
  },

  mlTraining: {
    title: "ML Model Training & Results",
    models: [
      { name: "Logistic Regression", accuracy: "97.06%", f1: "0.9706", precision: "0.9707", recall: "0.9706" },
      { name: "Multinomial Naive Bayes", accuracy: "96.69%", f1: "0.9669", precision: "0.9670", recall: "0.9669" },
      { name: "Linear SVM (Tuned)", accuracy: "97.25%", f1: "0.9725", precision: "0.9726", recall: "0.9725" },
      { name: "SGD Classifier", accuracy: "97.03%", f1: "0.9703", precision: "0.9703", recall: "0.9703" },
      { name: "Random Forest", accuracy: "94.44%", f1: "0.9445", precision: "0.9454", recall: "0.9444" }
    ],
    bestModel: "Linear SVM (Tuned) — 97.25% Test Accuracy",
    cvAccuracy: "96.17% ± 0.45%",
    perClass: [
      { domain: "Astrophysics (astro-ph.GA)", precision: "0.99", recall: "0.98", f1: "0.98" },
      { domain: "NLP (cs.CL)", precision: "0.98", recall: "0.98", f1: "0.98" },
      { domain: "Computer Vision (cs.CV)", precision: "0.97", recall: "0.95", f1: "0.96" },
      { domain: "High Energy Physics (hep-th)", precision: "0.97", recall: "0.97", f1: "0.97" },
      { domain: "Combinatorics (math.CO)", precision: "0.96", recall: "0.98", f1: "0.97" },
      { domain: "Neuroscience (q-bio.NC)", precision: "0.96", recall: "0.97", f1: "0.97" }
    ]
  },
  
  security: {
    title: "Security Implementation",
    measures: [
      "Row Level Security (RLS) on all database tables",
      "JWT-based authentication with session refresh",
      "User data isolation — users only access their own data",
      "Secure Edge Functions with request validation",
      "HTTPS encryption for all API communications",
      "Environment variables for sensitive API keys"
    ]
  },
  
  testing: {
    title: "Testing Strategy",
    categories: [
      {
        type: "Unit Testing",
        items: ["Component rendering", "Citation format generation", "Form validation"]
      },
      {
        type: "Integration Testing",
        items: ["API endpoint connectivity", "Database operations", "Authentication flow"]
      },
      {
        type: "ML Validation",
        items: ["5-fold cross-validation (96.17%)", "Custom test abstracts (100%)", "Per-class F1 analysis"]
      }
    ]
  },
  
  timeline: {
    title: "Project Timeline (12 Weeks)",
    phases: [
      { week: "1-2", phase: "Planning & Design", tasks: "Requirements, architecture, UI mockups" },
      { week: "3-4", phase: "Backend Development", tasks: "Database schema, RLS policies, Edge Functions" },
      { week: "5-6", phase: "Frontend Development", tasks: "React components, routing, state management" },
      { week: "7-8", phase: "AI & ML Integration", tasks: "Gemini integration, ML training pipeline, classification" },
      { week: "9-10", phase: "Testing & Refinement", tasks: "Bug fixes, model tuning, performance optimization" },
      { week: "11-12", phase: "Deployment", tasks: "Production deployment, documentation, conference paper" }
    ]
  },
  
  futureEnhancements: {
    title: "Future Enhancements",
    items: [
      "Paper similarity detection using SciBERT embeddings",
      "Hierarchical classification for fine-grained arXiv subcategories",
      "PDF parsing via GROBID for full-text analysis",
      "Collaborative research projects with team sharing",
      "Export to reference managers (Zotero, Mendeley)",
      "Recommendation engine based on reading history"
    ]
  },
  
  conclusion: {
    title: "Conclusion",
    points: [
      "Successfully built AI-powered research assistant with ML classification",
      "Integrated with 200M+ paper database via Semantic Scholar",
      "Trained 5 classifiers — best: Linear SVM at 97.25% accuracy",
      "Automated summarization reduces paper review time by ~70%",
      "Multi-format citations eliminate manual formatting errors",
      "Secure, scalable architecture with RLS protection"
    ]
  },
  
  references: {
    title: "References",
    items: [
      "Semantic Scholar API — api.semanticscholar.org",
      "Google Gemini 2.5 Flash — ai.google.dev",
      "Cornell arXiv Dataset — kaggle.com (CC0 License)",
      "scikit-learn — scikit-learn.org",
      "React 18 — react.dev",
      "ShadCN/UI — ui.shadcn.com"
    ]
  }
};

export const designConfig = {
  colors: {
    primary: "6366F1",
    secondary: "8B5CF6",
    accent: "10B981",
    background: "FFFFFF",
    text: "1F2937",
    lightGray: "F3F4F6",
    darkBlue: "1E3A5F"
  },
  fonts: {
    title: { face: "Arial", size: 36, bold: true },
    subtitle: { face: "Arial", size: 24, bold: false },
    heading: { face: "Arial", size: 28, bold: true },
    body: { face: "Arial", size: 18, bold: false },
    small: { face: "Arial", size: 14, bold: false }
  }
};
